export declare const ACCOUNT_EVENTS: {
    createEmployees: string;
    validateEmployees: string;
    checkEmployee: string;
    updateEmployee: string;
    sendInvite: string;
    getEmployees: string;
    getEmployee: string;
    updateEmployeeWithIntent: string;
    createEmployeeSalaryAddon: string;
    updateEmployeeSalaryAddon: string;
    deleteEmployeeSalaryAddon: string;
    createGroup: string;
    getGroup: string;
    getGroups: string;
    updateGroup: string;
    deleteGroup: string;
    getGroupEmployees: string;
    addEmployeesToGroup: string;
    removeEmployeeFromGroup: string;
    terminateEmployee: string;
    addOrganization: string;
    getOrganization: string;
    fetchActiveEmployeesData: string;
    fetchEmployeesForWorksheet: string;
};
